const mongoose = require("mongoose");

const activitySchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    action: {
      type: String,
      enum: [
        "join_workspace",
        "leave_workspace",
        "board_created",
        "join_board",
        "leave_board",
        "member_invited",
        "member_removed",
        "member_left",
        "join_card",
        "leave_card",
        "checklist_added",
        "checklist_completed",
        "checklist_uncompleted",
        "comment_added",
        "note_added",
        "card_completed",
        "card_uncompleted",
        "card_moved",
        "workspace_created",
        "workspace_updated", 
        "workspace_hidden", 
        "board_created", 
        "board_updated", 
        "board_hidden", 
        "board_deleted",
        "list_order_updated",
        "list_created", 
        "list_updated", 
        "list_hidden", 
        "list-order",
        "card_created", 
        "card-order",
        "card_updated", 
        "member_added",
        "card_hidden",
        "checklist_item_added", 
        "checklist_item_toggled",
        "checklist_item_completed",
        "checklist_item_uncompleted",
        "update-card-order",
        "member_removed_from_card",
      ],
      required: true,
    },
    target: {
      type: mongoose.Schema.Types.ObjectId,
      refPath: "targetModel",
      required: true,
    },
    targetModel: {
      type: String,
      enum: ["Workspace", "Board", "List", "Card",],
      required: true,
    },
    details: { type: String },
    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Activity", activitySchema);